### ISSUE TITLE
Mac OS X Sample App does not compile

### ISSUE THREAD

**Issue by sebsto** [DigitalDJ/AudioStreamer#2]
After your last changes to nicely handle background streaming for iOS, the Mac OS X demo application is not compiling anymore.

I made the following modification to correct this - could you please integrate in your repository ?  

diff --git a/Classes/AudioStreamer.h b/Classes/AudioStreamer.h
index 2236457..0857f17 100644
--- a/Classes/AudioStreamer.h
+++ b/Classes/AudioStreamer.h
@@ -104,7 +104,9 @@

 @interface AudioStreamer : NSObject
 {
+#if TARGET_OS_IPHONE  
    UIBackgroundTaskIdentifier bgTaskId;
+#endif  
    NSURL *url;

```
//
```

diff --git a/Classes/AudioStreamer.m b/Classes/AudioStreamer.m
index 4e8e56a..190cdcd 100644
--- a/Classes/AudioStreamer.m
+++ b/Classes/AudioStreamer.m
@@ -30,7 +30,7 @@
 NSString \* const ASUpdateMetadataNotification = @"ASUpdateMetadataNotification";
 #endif

-static AudioStreamer *__streamer = nil;
+//static AudioStreamer *__streamer = nil;

 NSString \* const AS_NO_ERROR_STRING = @"No error.";
 NSString \* const AS_FILE_STREAM_GET_PROPERTY_FAILED_STRING = @"File stream get property failed.";
@@ -1215,7 +1215,9 @@ - (void)pause
        else if (state == AS_PAUSED)
        {
            err = AudioQueueStart(audioQueue, NULL);
+#if TARGET_OS_IPHONE  
            bgTaskId = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:NULL];
+#endif  
            if (err)
            {
                [self failWithErrorCode:AS_AUDIO_QUEUE_START_FAILED];
@@ -1807,8 +1809,9 @@ - (void)enqueueBuffer
                if (self.state == AS_BUFFERING)
                {
                    err = AudioQueueStart(audioQueue, NULL);
+#if TARGET_OS_IPHONE                    
##                     bgTaskId = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:NULL];

+#endif  
                    if (err)
                    {
                        [self failWithErrorCode:AS_AUDIO_QUEUE_START_FAILED];
@@ -1821,8 +1824,9 @@ - (void)enqueueBuffer
                    self.state = AS_WAITING_FOR_QUEUE_TO_START;

```
                err = AudioQueueStart(audioQueue, NULL);
```

+#if TARGET_OS_IPHONE                    
##                     bgTaskId = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:NULL];

+#endif  
                    if (err)
                    {
                        [self failWithErrorCode:AS_AUDIO_QUEUE_START_FAILED];
@@ -2300,8 +2304,9 @@ - (void)handlePropertyChangeForQueue:(AudioQueueRef)inAQ
    propertyID:(AudioQueuePropertyID)inID
 {
    NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
+#if TARGET_OS_IPHONE    
##     UIBackgroundTaskIdentifier newTaskId = UIBackgroundTaskInvalid;

+#endif 
    @synchronized(self)
    {
        if (inID == kAudioQueueProperty_IsRunning)
@@ -2327,17 +2332,21 @@ - (void)handlePropertyChangeForQueue:(AudioQueueRef)inAQ
                // thread destruction order and seems to avoid this crash bug -- or
                // at least I haven't had it since (nasty hard to reproduce error!)
                //
+#if TARGET_OS_IPHONE  
                newTaskId = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:NULL];
+#endif                

```
            [NSRunLoop currentRunLoop];

            self.state = AS_PLAYING;
```
- +
  +#if TARGET_OS_IPHONE  
              if (bgTaskId != UIBackgroundTaskInvalid) {
                  [[UIApplication sharedApplication] endBackgroundTask: bgTaskId];
              }
  
  ```
          bgTaskId = newTaskId;
  ```
  
  +#endif  
          }
          else
          {

**Comment by sebsto** [comment]
Oup, there is one small mistake, around line 34 in AudioStreamer.m
it should be

#if TARGET_OS_IPHONE  
static AudioStreamer *__streamer = nil;
#endif

**Comment by DigitalDJ** [comment]
Fixed by sebsto
