### ISSUE TITLE
SHOUTCAST_METADATA does not compile

### ISSUE THREAD

**Issue by sebsto** [DigitalDJ/AudioStreamer#3]
When defining SHOUTCAST_METADATA in AudioStreamer.h, the code does not compile.
I corrected this, here is my diff file

diff --git a/Classes/AudioStreamer.h b/Classes/AudioStreamer.h
index 0857f17..22fd1ab 100644
--- a/Classes/AudioStreamer.h
+++ b/Classes/AudioStreamer.h
@@ -11,6 +11,7 @@
 //  this copyright and permission notice. Attribution in compiled projects is
 //  appreciated but not required.
 //
+#define SHOUTCAST_METADATA

 #if TARGET_OS_IPHONE  
 #import <UIKit/UIKit.h>
@@ -101,6 +102,9 @@

 extern NSString \* const ASStatusChangedNotification;
 extern NSString \* const ASPresentAlertWithTitleNotification;
+#ifdef SHOUTCAST_METADATA
+extern NSString \* const ASUpdateMetadataNotification;
+#endif

 @interface AudioStreamer : NSObject
 {
diff --git a/Classes/AudioStreamer.m b/Classes/AudioStreamer.m
index 134ebb8..323634d 100644
--- a/Classes/AudioStreamer.m
+++ b/Classes/AudioStreamer.m
@@ -1283,8 +1283,7 @@ - (void)updateMetaData:(NSString *)metaData
         notificationWithName:ASUpdateMetadataNotification
         object:self
         userInfo:userInfo];
-       [[NSNotificationCenter defaultCenter]
-        postNotification:notification];
-       [[NSNotificationCenter defaultCenter] postNotification:notification];
  }
  #endif

@@ -1422,10 +1421,13 @@ - (void)handleReadFromStream:(CFReadStreamRef)aStream
                        }
                }
-   
              UInt8 bytes[kAQDefaultBufSize];
              CFIndex length;
-               //UInt8 bytesNoMetaData[kAQDefaultBufSize];
-               //int lengthNoMetaData = 0;
  +#ifdef SHOUTCAST_METADATA
-               UInt8 bytesNoMetaData[kAQDefaultBufSize];
- ```
            int lengthNoMetaData = 0;
  ```
  
  +#endif        
  
  ```
          @synchronized(self)
          {
  ```

**Comment by DigitalDJ** [comment]
Fixed by sebsto
