### ISSUE TITLE
iPhone apps crashes in SHOUTCAST_METADATA mode when returning from Background

### ISSUE THREAD

**Issue by sebsto** [DigitalDJ/AudioStreamer#4]
When returning from background, and using SHOUTCAST_METATDATA, the iPhone demo application is crashing

Reproductible : always
Cause : currentArtist and currentTitle are not properly retained
Modifications :
Declare currentArtist and currentTitle as @property with 'retain' attribute
in the ViewController .h
@property (retain) NSString\* currentArtist;
@property (retain) NSString\* currentTitle;

In the ViewController.m
Just after @implementation :
@synthesize currentArtist, currentTitle;

and in - (void)metadataChanged:(NSNotification *)aNotification

```
self.currentArtist = streamArtist;
self.currentTitle = streamTitle;
```

**Comment by DigitalDJ** [comment]
Fixed by sebsto
